name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - kiraryuuki

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: KiRaRyuuKi
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#d9381e&color_dots=#e7e5e2,#eebd9d,#e58a63,#d4744c,#8f3d1e
            dist/github-contribution-grid-snake-dark.svg?color_snake=#f2603d&color_dots=#302e2c,#56534f,#9c9791,#ef9a72,#f4ab86

      - name: Deploy to output branch KiRaRyuuKi
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
